openapi: 3.0.1
info:
  title: Restaurant Manager
  description: >-
    Projeto relativo ao curso MBA em Engenharia de Software da Universidade
    Federal do Rio de Janeiro implementado pelo Grupo D para a segunda tarefa da
    disciplina Arquitetura de Serviços.
  version: v1.0.0
externalDocs:
  description: Github
  url: https://github.com/Hieron/restaurants-service-repository
servers:
  - url: http://localhost:5000
    description: restaurants
paths:
  /api/restaurants:
    get:
      summary: Get restaurants
      tags: 
        - Restaurants
      parameters:
        - in: query
          name: postalCode
          schema:
            type: string
          description: Postal code of the restaurant
        - in: query
          name: streetAddress
          schema:
            type: string
          description: Street address of the restaurant
        - in: query
          name: addressLocality
          schema:
            type: string
          description: Locality of the restaurant
        - in: query
          name: addressRegion
          schema:
            type: string
          description: Region of the restaurant
        - in: query
          name: addressCountry
          schema:
            type: string
          description: Country of the restaurant
      responses:
        '200':
          description: List of restaurants
    post:
      summary: Create a restaurant
      tags: 
        - Restaurants
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Restaurant'
      responses:
        '201':
          description: Restaurant created
    servers:
      - url: http://localhost:5000
  /api/restaurants/{restaurant_id}:
    parameters:
      - in: path
        name: restaurant_id
        required: true
        schema:
          type: integer
          format: int64
        description: ID of the restaurant
    get:
      summary: Get a restaurant by ID
      tags: 
        - Restaurants
      responses:
        '200':
          description: Restaurant details
        '404':
          description: Restaurant not found
    put:
      summary: Update a restaurant
      tags: 
        - Restaurants
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Restaurant'
      responses:
        '200':
          description: Restaurant updated
        '404':
          description: Restaurant not found
    delete:
      summary: Delete a restaurant
      tags: 
        - Restaurants
      responses:
        '204':
          description: Restaurant deleted
        '404':
          description: Restaurant not found
    servers:
      - url: http://localhost:5000
components:
  schemas:
    Restaurant:
      type: object
      properties:
        name:
          type: string
        url:
          type: string
        menu:
          type: string
        telephone:
          type: string
        priceRange:
          type: string
        address:
          $ref: '#/components/schemas/Address'
      required:
        - name
    Address:
      type: object
      properties:
        postalCode:
          type: string
        streetAddress:
          type: string
        addressLocality:
          type: string
        addressRegion:
          type: string
        addressCountry:
          type: string
      required:
        - restaurant_id
        - postalCode
        - streetAddress
        - addressLocality
        - addressRegion
        - addressCountry
